
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7D000, LENGTH = 0x3000
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x41620;
c6_A0 = .;
. += 0x1200;
. = 0x45220;
c6_A1 = .;
. += 0x1200;
. = 0x40400;
c6_B0 = .;
. += 0x1220;
. = 0x44000;
c6_B1 = .;
. += 0x1220;
. = 0x48000;
c6_B2 = .;
. += 0x1220;
. = 0x4D220;
c6_Q = .;
. += 0x284;
. = 0x49220;
c6_O = .;
. += 0x1000;
. = 0x4C000;
c6_P = .;
. += 0x1220;
. = 0x50400;
op_O = .;
. += 0x1000;
. = 0x78000;
nm_O = .;
. += 0x1000;
. = 0x7C000;
nm_R = .;
. += 0x1000;
. = 0x70400;
nm_F = .;
. += 0x1220;
. = 0x74000;
nm_FN = .;
. += 0x1220;
. = 0x71620;
nm_gain = .;
. += 0x1000;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_tb.mlir.prj\layer_fused_relay.o)
PROVIDE(main = core_4_4);
