
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7D4A4, LENGTH = 0x2B5C
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x51620;
c2_A0 = .;
. += 0x1200;
. = 0x55220;
c2_A1 = .;
. += 0x1200;
. = 0x50400;
c2_B0 = .;
. += 0x1220;
. = 0x54000;
c2_B1 = .;
. += 0x1220;
. = 0x58000;
c2_B2 = .;
. += 0x1220;
. = 0x5D220;
c2_Q = .;
. += 0x284;
. = 0x59220;
c2_O = .;
. += 0x1000;
. = 0x5C000;
c2_P = .;
. += 0x1220;
. = 0x61620;
c7_A0 = .;
. += 0x1200;
. = 0x65220;
c7_A1 = .;
. += 0x1200;
. = 0x60400;
c7_B0 = .;
. += 0x1220;
. = 0x64000;
c7_B1 = .;
. += 0x1220;
. = 0x68000;
c7_B2 = .;
. += 0x1220;
. = 0x6D220;
c7_Q = .;
. += 0x284;
. = 0x69220;
c7_O = .;
. += 0x1000;
. = 0x6C000;
c7_P = .;
. += 0x1220;
. = 0x71620;
c3_A0 = .;
. += 0x1200;
. = 0x75220;
c3_A1 = .;
. += 0x1200;
. = 0x70400;
c3_B0 = .;
. += 0x1220;
. = 0x74000;
c3_B1 = .;
. += 0x1220;
. = 0x78000;
c3_B2 = .;
. += 0x1220;
. = 0x7D220;
c3_Q = .;
. += 0x284;
. = 0x79220;
c3_O = .;
. += 0x1000;
. = 0x7C000;
c3_P = .;
. += 0x1220;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_tb.mlir.prj\layer_fused_bcast_kc256.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_tb.mlir.prj\layer_fused_bcast_wrapper.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_tb.mlir.prj\rope_il.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_tb.mlir.prj\layer_fused_relay.o)
PROVIDE(main = core_5_2);
