
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C284, LENGTH = 0x3D7C
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
/* No tile with memory exists to the west. */
. = 0x50000;
. += 0x10000;
. = 0x6C000;
sc4_Qs = .;
. += 0x284;
. = 0x64000;
sc4_K = .;
. += 0x4000;
. = 0x68000;
sc4_It = .;
. += 0x410;
. = 0x60400;
sc4_Oh = .;
. += 0x200;
. = 0x7C000;
sc0_Qs = .;
. += 0x284;
. = 0x74000;
sc0_K = .;
. += 0x4000;
. = 0x78000;
sc0_It = .;
. += 0x410;
. = 0x70400;
sc0_Oh = .;
. += 0x200;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp.mlir.prj\flowkv_64d_h4_c256.o)
PROVIDE(main = core_0_2);
