
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7C284, LENGTH = 0x3D7C
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x4C000;
sc2_Qs = .;
. += 0x284;
. = 0x44000;
sc2_K = .;
. += 0x4000;
. = 0x48000;
sc2_It = .;
. += 0x410;
. = 0x40400;
sc2_Oh = .;
. += 0x200;
. = 0x51620;
c7_A0 = .;
. += 0x1200;
. = 0x55220;
c7_A1 = .;
. += 0x1200;
. = 0x50400;
c7_B0 = .;
. += 0x1220;
. = 0x54000;
c7_B1 = .;
. += 0x1220;
. = 0x58000;
c7_B2 = .;
. += 0x1220;
. = 0x5D220;
c7_Q = .;
. += 0x284;
. = 0x59220;
c7_O = .;
. += 0x1000;
. = 0x5C000;
c7_P = .;
. += 0x1220;
. = 0x68000;
va2_Iv = .;
. += 0x410;
. = 0x64000;
va2_V = .;
. += 0x4000;
. = 0x6C000;
va2_Of = .;
. += 0x200;
. = 0x7C000;
sc6_Qs = .;
. += 0x284;
. = 0x74000;
sc6_K = .;
. += 0x4000;
. = 0x78000;
sc6_It = .;
. += 0x410;
. = 0x70400;
sc6_Oh = .;
. += 0x200;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp.mlir.prj\flowkv_64d_h4_c256.o)
PROVIDE(main = core_6_3);
