
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7DAA0, LENGTH = 0x2560
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x41620;
c2_A0 = .;
. += 0x1200;
. = 0x45220;
c2_A1 = .;
. += 0x1200;
. = 0x40400;
c2_B0 = .;
. += 0x1220;
. = 0x44000;
c2_B1 = .;
. += 0x1220;
. = 0x48000;
c2_B2 = .;
. += 0x1220;
. = 0x4A220;
c2_Q = .;
. += 0x284;
. = 0x49220;
c2_O = .;
. += 0x1000;
. = 0x4C000;
c2_P = .;
. += 0x1220;
. = 0x4D220;
c2_gate = .;
. += 0x800;
. = 0x42820;
c2_up = .;
. += 0x800;
. = 0x46420;
c2_silu = .;
. += 0x800;
. = 0x4DA20;
c2_uni_partial = .;
. += 0x80;
. = 0x51620;
c5_A0 = .;
. += 0x1200;
. = 0x55220;
c5_A1 = .;
. += 0x1200;
. = 0x50400;
c5_B0 = .;
. += 0x1220;
. = 0x54000;
c5_B1 = .;
. += 0x1220;
. = 0x58000;
c5_B2 = .;
. += 0x1220;
. = 0x5A220;
c5_Q = .;
. += 0x284;
. = 0x59220;
c5_O = .;
. += 0x1000;
. = 0x5C000;
c5_P = .;
. += 0x1220;
. = 0x5D220;
c5_gate = .;
. += 0x800;
. = 0x52820;
c5_up = .;
. += 0x800;
. = 0x56420;
c5_silu = .;
. += 0x800;
. = 0x5DA20;
c5_uni_partial = .;
. += 0x80;
. = 0x68000;
nm_O = .;
. += 0x1000;
. = 0x6C000;
nm_R = .;
. += 0x1000;
. = 0x60400;
nm_F = .;
. += 0x1220;
. = 0x64000;
nm_FN = .;
. += 0x1220;
. = 0x61620;
nm_gain = .;
. += 0x1000;
. = 0x71620;
c6_A0 = .;
. += 0x1200;
. = 0x75220;
c6_A1 = .;
. += 0x1200;
. = 0x70400;
c6_B0 = .;
. += 0x1220;
. = 0x74000;
c6_B1 = .;
. += 0x1220;
. = 0x78000;
c6_B2 = .;
. += 0x1220;
. = 0x7A220;
c6_Q = .;
. += 0x284;
. = 0x79220;
c6_O = .;
. += 0x1000;
. = 0x7C000;
c6_P = .;
. += 0x1220;
. = 0x7D220;
c6_gate = .;
. += 0x800;
. = 0x72820;
c6_up = .;
. += 0x800;
. = 0x76420;
c6_silu = .;
. += 0x800;
. = 0x7DA20;
c6_uni_partial = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_decouple_tb.mlir.prj\layer_fused_bcast_kc256.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_decouple_tb.mlir.prj\layer_fused_unified_bcast.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_decouple_tb.mlir.prj\rope_il.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_decouple_tb.mlir.prj\layer_fused_relay.o)
PROVIDE(main = core_4_3);
