
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7D220, LENGTH = 0x2DE0
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
. = 0x41620;
c7_A0 = .;
. += 0x1200;
. = 0x45220;
c7_A1 = .;
. += 0x1200;
. = 0x40400;
c7_B0 = .;
. += 0x1220;
. = 0x44000;
c7_B1 = .;
. += 0x1220;
. = 0x48000;
c7_B2 = .;
. += 0x1220;
. = 0x4A220;
c7_Q = .;
. += 0x284;
. = 0x49220;
c7_O = .;
. += 0x1000;
. = 0x4C000;
c7_P = .;
. += 0x1220;
. = 0x4D220;
c7_gate = .;
. += 0x800;
. = 0x42820;
c7_up = .;
. += 0x800;
. = 0x46420;
c7_silu = .;
. += 0x800;
. = 0x4DA20;
c7_uni_partial = .;
. += 0x80;
. = 0x58000;
nm_O = .;
. += 0x1000;
. = 0x5C000;
nm_R = .;
. += 0x1000;
. = 0x50400;
nm_F = .;
. += 0x1220;
. = 0x54000;
nm_FN = .;
. += 0x1220;
. = 0x51620;
nm_gain = .;
. += 0x1000;
. = 0x70400;
mx_x = .;
. += 0x1220;
. = 0x74000;
mx_a = .;
. += 0x1220;
. = 0x78000;
mx_f = .;
. += 0x1220;
. = 0x7C000;
mx_o = .;
. += 0x1220;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_tb.mlir.prj\attn_concat.o)
PROVIDE(main = core_5_4);
