
MEMORY
{
   program (RX) : ORIGIN = 0, LENGTH = 0x0020000
   data (!RX) : ORIGIN = 0x7DAA0, LENGTH = 0x2560
}
ENTRY(__start)
SECTIONS
{
  . = 0x0;
  .text : {
     /* the __start symbol has to come at address zero. */
     *crt0.o(.text*)
     _ctors_start = .;
     _init_array_start = .;
     KEEP(SORT(*.init_array))
     _ctors_end = .;
     _init_array_end = .;
     _dtors_start = .;
     _dtors_end = .;
     *(.text*)
  } > program
  .data : {
     *(.data*)
     *(.rodata*)
  } > data
  .comment : {
     *(.comment*)
  }
  .symtab : {
     *(.symtab)
  }
  .shstrtab : {
     *(.shstrtab)
  }
  .strtab : {
     *(.strtab)
  }
  .stack_sizes : {
     *(.stack_sizes)
  }

. = 0x70000;
_sp_start_value_DM_stack = .;
. += 0x400; /* stack */
/* No tile with memory exists to the south. */
. = 0x40000;
. += 0x10000;
. = 0x51620;
c0_A0 = .;
. += 0x1200;
. = 0x55220;
c0_A1 = .;
. += 0x1200;
. = 0x50400;
c0_B0 = .;
. += 0x1220;
. = 0x54000;
c0_B1 = .;
. += 0x1220;
. = 0x58000;
c0_B2 = .;
. += 0x1220;
. = 0x5A220;
c0_Q = .;
. += 0x284;
. = 0x59220;
c0_O = .;
. += 0x1000;
. = 0x5C000;
c0_P = .;
. += 0x1220;
. = 0x5D220;
c0_gate = .;
. += 0x800;
. = 0x52820;
c0_up = .;
. += 0x800;
. = 0x56420;
c0_silu = .;
. += 0x800;
. = 0x5DA20;
c0_uni_partial = .;
. += 0x80;
. = 0x61620;
c5_A0 = .;
. += 0x1200;
. = 0x65220;
c5_A1 = .;
. += 0x1200;
. = 0x60400;
c5_B0 = .;
. += 0x1220;
. = 0x64000;
c5_B1 = .;
. += 0x1220;
. = 0x68000;
c5_B2 = .;
. += 0x1220;
. = 0x6A220;
c5_Q = .;
. += 0x284;
. = 0x69220;
c5_O = .;
. += 0x1000;
. = 0x6C000;
c5_P = .;
. += 0x1220;
. = 0x6D220;
c5_gate = .;
. += 0x800;
. = 0x62820;
c5_up = .;
. += 0x800;
. = 0x66420;
c5_silu = .;
. += 0x800;
. = 0x6DA20;
c5_uni_partial = .;
. += 0x80;
. = 0x71620;
c1_A0 = .;
. += 0x1200;
. = 0x75220;
c1_A1 = .;
. += 0x1200;
. = 0x70400;
c1_B0 = .;
. += 0x1220;
. = 0x74000;
c1_B1 = .;
. += 0x1220;
. = 0x78000;
c1_B2 = .;
. += 0x1220;
. = 0x7A220;
c1_Q = .;
. += 0x284;
. = 0x79220;
c1_O = .;
. += 0x1000;
. = 0x7C000;
c1_P = .;
. += 0x1220;
. = 0x7D220;
c1_gate = .;
. += 0x800;
. = 0x72820;
c1_up = .;
. += 0x800;
. = 0x76420;
c1_silu = .;
. += 0x800;
. = 0x7DA20;
c1_uni_partial = .;
. += 0x80;
  .bss : { *(.bss*) } > data
}
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_tb.mlir.prj\layer_fused_bcast_kc256.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_tb.mlir.prj\layer_fused_unified_bcast.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_tb.mlir.prj\rope_il.o)
INPUT(decode_layer_f3best_2048x8192_d64_g32_s256_a4_kv8_mc_preq_vexp_vreg_dq8_qp_mxp_ub_tb.mlir.prj\layer_fused_relay.o)
PROVIDE(main = core_3_2);
